### ISSUE TITLE
pyproject.toml [tool.setuptools] 

### ISSUE THREAD

**Issue by thiasB** [ISI-MIP/isimip-qa#9]
https://github.com/ISI-MIP/isimip-qa/blob/6043e6cba3042e28a27f465a2789c59e3664b969/pyproject.toml#L49-L50

I had to remove this section in the [QC-Tool](https://github.com/ISI-MIP/isimip-qc/commit/35a64feab458ae748b2c87738f8cdfe6cdb30e7c) as the building of new releases for PyPi struggled with including all project modules (subfolders). I don't know exactly why but after removing, `python -m build` again autodetects all submodules. Explicitly defining only the main package excludes (changes in) the submodules, it seems.

**Comment by jochenklar** [comment]
Yes, this was a bug here, the trick is to include:

```
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
```

The `setuptools-scm` looks for all packages in the repo. I think without `packages = ["isimip_qa"]` `build` would also pick up other python modules in the repo, like a possible `testing` directory, which we might not want. I will double check if I add tests to https://github.com/ISI-MIP/isimip-qc .
